sonar.projectKey=estebancasas9817_gymshark
sonar.organization=estebancasas9817

# Files to exclude / include
sonar.sources=
sonar.exclusions=**/node_modules/**, **/.next/**, **/*.test.ts, **/*.test.tsx

sonar.sourceEncoding=UTF-8