import type { Metadata } from 'next';
import { Montserrat, Roboto } from 'next/font/google';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { CartProvider } from './context/cart-context';
import { SessionProvider } from 'next-auth/react';
import { CartDrawer } from '@/features/cart-drawer';
import { WishlistProvider } from './context/wishlist-context';

const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--font-montserrat',
	display: 'swap',
});

const roboto = Roboto({
	subsets: ['latin'],
	variable: '--font-roboto',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const messages = await getMessages();

	return (
		<html lang="en">
			<body className={`${montserrat.variable} ${roboto.variable} antialiased`}>
				<NextIntlClientProvider messages={messages}>
					<SessionProvider>
						<CartProvider>
							<WishlistProvider>
								<>
									<CartDrawer />
									{children}
								</>
							</WishlistProvider>
						</CartProvider>
					</SessionProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
